on: [push, pull_request]
jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    env:
      CXX: g++
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: catchorg/Catch2
        path: catch
    - name: Install catch
      working-directory: catch
      run: >
        mkdir build
        && cd build
        && cmake -DCMAKE_BUILD_TYPE=Release -DCATCH_BUILD_TESTING=Off ..
        && sudo make install
    - name: Info
      run: cmake --version && $CXX --version && uname -a
    - name: Build
      run: >
        mkdir -p build
        && cd build
        && cmake ..
        && make
    - name: Build Test
      run: cd build && make sgnl-test
    - name: Run Test
      run: ./build/test/sgnl-test
    - name: Build example
      run: >
        cd build
        && make example
    - name: Run example
      run: ./build/example
    - name: Install signal-wrangler
      run: cd build && sudo make install
    - name: Test install
      run: >
        cd example
        && $CXX -std=c++17 -Wall -pthread -o example example.cpp
        && ./example
